In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('/content/sample_data/Advertising.csv')

In [45]:
X = df.drop('sales', axis=1)
y = df['sales']

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
scaler = StandardScaler()

In [18]:
scaler.fit(X_train)

StandardScaler()

In [19]:
X_train = scaler.transform(X_train)

In [20]:
X_test = scaler.transform(X_test)

In [21]:
from sklearn.linear_model import Ridge

In [22]:
model = Ridge(alpha=100)

In [23]:
model.fit(X_train,y_train)

Ridge(alpha=100)

In [24]:
y_pred = model.predict(X_test)

In [25]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [26]:
mean_squared_error(y_test,y_pred)

7.34177578903413

In [27]:
model2 = Ridge(alpha=1)

In [28]:
model2.fit(X_train,y_train)

Ridge(alpha=1)

In [29]:
y_pred2 = model2.predict(X_test)

In [30]:
mean_squared_error(y_test,y_pred2)

2.319021579428752

#split data into 3: Test, Validation, Train

In [68]:
X_train, X_other, y_train, y_other = train_test_split(X, y, test_size=0.3, random_state=101)

In [53]:
X_eval, X_test, y_eval, y_test = train_test_split(X_other, y_other, test_size=0.5, random_state=101)

In [69]:
scaler = StandardScaler()

In [70]:
scaler.fit(X_train)

StandardScaler()

In [71]:
X_train = scaler.transform(X_train)

In [72]:
X_test = scaler.transform(X_test)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [73]:
X_test

array([[-1.81157372, -1.6012956 , -1.48085784],
       [-1.81575718, -1.50653432, -1.50812956],
       [-1.79317778, -1.68363672, -1.4745308 ],
       [-1.7842897 , -1.67949667, -1.47823975],
       [-1.77996538, -1.56817515, -1.51685651],
       [-1.81427818, -1.64223616, -1.48063966],
       [-1.79926281, -1.68363672, -1.50267521],
       [-1.79719221, -1.5129744 , -1.43853212],
       [-1.78534613, -1.5718552 , -1.50878408],
       [-1.81292595, -1.64039614, -1.42675074],
       [-1.81946172, -1.62245589, -1.41256945],
       [-1.81967301, -1.52585458, -1.42216909],
       [-1.7921777 , -1.65695636, -1.46318576],
       [-1.81160189, -1.6528163 , -1.51882007],
       [-1.80541827, -1.6155558 , -1.43656856],
       [-1.79317778, -1.68133669, -1.44529551],
       [-1.80481258, -1.62797597, -1.50900225],
       [-1.79403701, -1.53275467, -1.35584427],
       [-1.78372627, -1.49411415, -1.50987495],
       [-1.7823177 , -1.47065383, -1.429587  ],
       [-1.81856024, -1.60313563, -1.483

In [74]:
X_eval = scaler.transform(X_eval)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [75]:
model_A = Ridge(alpha=100)

In [80]:
model_A.fit(X_train,y_train)

Ridge(alpha=100)

In [81]:
y_eval_pred = model_A.predict(X_eval)

In [82]:
mean_squared_error(y_eval,y_eval_pred)

7.320101458823871

In [83]:
model_B = Ridge(alpha=1)

In [84]:
model_B.fit(X_train,y_train)

Ridge(alpha=1)

In [85]:
y_eval_pred_B = model_B.predict(X_eval)

In [86]:
mean_squared_error(y_eval,y_eval_pred_B)

2.383783075056986

In [87]:
y_final_pred = model_B.predict(X_test)

In [88]:
mean_squared_error(y_test,y_final_pred)

130.05131347685392

#cross_val_score *function*

In [89]:
X = df.drop('sales', axis=1)
y = df['sales']


In [91]:
X_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [92]:
scaler = StandardScaler()

In [93]:
scaler.fit(X_train)

StandardScaler()

In [94]:
X_train = scaler.transform(X_train)

In [95]:
X_test = scaler.transform(x_test)

In [96]:
model = Ridge(alpha=100)

In [97]:
from sklearn.model_selection import cross_val_score

In [98]:
scores = cross_val_score(model,X_train,y_train,scoring='neg_mean_squared_error',cv=5)

In [99]:
scores

array([ -9.32552967,  -4.9449624 , -11.39665242,  -7.0242106 ,
        -8.38562723])

In [100]:
abs(scores.mean())

np.float64(8.215396464543607)

In [101]:
model = Ridge(alpha=1)

In [102]:
scores = cross_val_score(model,X_train,y_train,scoring='neg_mean_squared_error',cv=5)

In [103]:
scores

array([-3.15513238, -1.58086982, -5.40455562, -2.21654481, -4.36709384])

In [104]:
abs(scores.mean())

np.float64(3.344839296530695)

In [105]:
model.fit(X_train,y_train)

Ridge(alpha=1)

In [106]:
y_final_test_pred = model.predict(X_test)

In [107]:
mean_squared_error(y_test,y_final_test_pred)

2.319021579428752

#cross_validate function

In [108]:
X = df.drop('sales', axis=1)
y = df['sales']

In [109]:
X_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [110]:
scaler = StandardScaler()

In [111]:
scaler.fit(X_train)

StandardScaler()

In [112]:
X_test = scaler.transform(x_test)

In [113]:
X_train = scaler.transform(X_train)

In [114]:
from sklearn.model_selection import cross_validate

In [121]:
model = Ridge(alpha=1)

In [122]:
scores = cross_validate(model,X_train,y_train,
                        scoring=['neg_mean_squared_error','neg_mean_absolute_error'],cv=10)

In [123]:
scores = pd.DataFrame(scores)

In [124]:
scores

fit_time  score_time  test_neg_mean_squared_error  \
0  0.001792    0.001473                    -2.962508   
1  0.001302    0.001373                    -3.057378   
2  0.001235    0.001248                    -2.173740   
3  0.001236    0.001260                    -0.833034   
4  0.001186    0.001304                    -3.464018   
5  0.001210    0.001212                    -8.232647   
6  0.001196    0.001204                    -1.905864   
7  0.001144    0.001256                    -2.765048   
8  0.001148    0.001208                    -4.989505   
9  0.001206    0.001217                    -2.846438   

   test_neg_mean_absolute_error  
0                     -1.457174  
1                     -1.555308  
2                     -1.238770  
3                     -0.768938  
4                     -1.434489  
5                     -1.494316  
6                     -1.081362  
7                     -1.250011  
8                     -1.580971  
9                     -1.223326

In [125]:
scores.mean()

fit_time                        0.001265
score_time                      0.001275
test_neg_mean_squared_error    -3.323018
test_neg_mean_absolute_error   -1.308467
dtype: float64

In [126]:
model.fit(X_train,y_train)

Ridge(alpha=1)

In [127]:
y_final_pred = model.predict(X_test)

In [128]:
mean_squared_error(y_test,y_final_pred)

2.319021579428752

#grid search


In [131]:
X = df.drop('sales', axis=1)
y = df['sales']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)
scaler = StandardScaler()
scaler.fit(X_train)

X_test = scaler.transform(X_test)
X_train = scaler.transform(X_train)

In [132]:
from sklearn.linear_model import ElasticNet

In [133]:
base_net_model = ElasticNet()

In [134]:
param_grid = {'alpha':[0.1,1,5,10,50,100],'l1_ratio':[.1,.5,.7,.95,.99,1]}

In [135]:
from sklearn.model_selection import GridSearchCV

In [136]:
grid_model = GridSearchCV(estimator=base_net_model,
                          param_grid=param_grid,
                          scoring='neg_mean_squared_error',
                          cv=5,
                          verbose=2)

In [139]:
grid_model.fit(X_train,y_train)

Fitting 5 folds for each of 36 candidates, totalling 180 fits
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=0.1,

GridSearchCV(cv=5, estimator=ElasticNet(),
             param_grid={'alpha': [0.1, 1, 5, 10, 50, 100],
                         'l1_ratio': [0.1, 0.5, 0.7, 0.95, 0.99, 1]},
             scoring='neg_mean_squared_error', verbose=2)

In [141]:
grid_model.best_estimator_

ElasticNet(alpha=0.1, l1_ratio=1)

In [142]:
grid_model.best_params_

{'alpha': 0.1, 'l1_ratio': 1}

In [143]:
pd.DataFrame(grid_model.cv_results_)

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_alpha  \
0        0.001627      0.000131         0.000929        0.000018          0.1   
1        0.001838      0.000344         0.001479        0.001020          0.1   
2        0.001481      0.000035         0.000907        0.000011          0.1   
3        0.001535      0.000127         0.000896        0.000012          0.1   
4        0.001477      0.000020         0.000971        0.000139          0.1   
5        0.001514      0.000090         0.000904        0.000029          0.1   
6        0.001466      0.000016         0.000903        0.000019          1.0   
7        0.001488      0.000014         0.000897        0.000021          1.0   
8        0.001473      0.000028         0.000887        0.000032          1.0   
9        0.001485      0.000020         0.000882        0.000017          1.0   
10       0.001455      0.000023         0.000885        0.000021          1.0   
11       0.001452      0.000025         0.000896        0.000006          1.0   
12       0.001538      0.000067         0.000910        0.000025          5.0   
13       0.001498      0.000023         0.000902        0.000015          5.0   
14       0.001481      0.000024         0.000914        0.000024          5.0   
15       0.001496      0.000028         0.000906        0.000018          5.0   
16       0.001498      0.000021         0.000924        0.000050          5.0   
17       0.001599      0.000139         0.001035        0.000145          5.0   
18       0.002370      0.000716         0.001234        0.000028         10.0   
19       0.001879      0.000063         0.001262        0.000022         10.0   
20       0.001235      0.000088         0.000827        0.000013         10.0   
21       0.001124      0.000016         0.000780        0.000005         10.0   
22       0.001119      0.000017         0.000795        0.000015         10.0   
23       0.001132      0.000021         0.000795        0.000016         10.0   
24       0.001129      0.000017         0.000796        0.000017         50.0   
25       0.001160      0.000015         0.000820        0.000037         50.0   
26       0.001218      0.000058         0.000833        0.000027         50.0   
27       0.001195      0.000050         0.000807        0.000012         50.0   
28       0.001155      0.000012         0.000798        0.000012         50.0   
29       0.001143      0.000023         0.000794        0.000013         50.0   
30       0.001199      0.000145         0.000895        0.000130        100.0   
31       0.001451      0.000052         0.000984        0.000046        100.0   
32       0.001319      0.000096         0.000922        0.000054        100.0   
33       0.001134      0.000019         0.000792        0.000005        100.0   
34       0.001157      0.000032         0.000882        0.000177        100.0   
35       0.001561      0.000053         0.000916        0.000010        100.0   

    param_l1_ratio                            params  split0_test_score  \
0             0.10   {'alpha': 0.1, 'l1_ratio': 0.1}          -3.453021   
1             0.50   {'alpha': 0.1, 'l1_ratio': 0.5}          -3.325440   
2             0.70   {'alpha': 0.1, 'l1_ratio': 0.7}          -3.269880   
3             0.95  {'alpha': 0.1, 'l1_ratio': 0.95}          -3.213052   
4             0.99  {'alpha': 0.1, 'l1_ratio': 0.99}          -3.208124   
5             1.00     {'alpha': 0.1, 'l1_ratio': 1}          -3.206943   
6             0.10     {'alpha': 1, 'l1_ratio': 0.1}          -9.827475   
7             0.50     {'alpha': 1, 'l1_ratio': 0.5}          -8.707071   
8             0.70     {'alpha': 1, 'l1_ratio': 0.7}          -7.920870   
9             0.95    {'alpha': 1, 'l1_ratio': 0.95}          -6.729435   
10            0.99    {'alpha': 1, 'l1_ratio': 0.99}          -6.521344   
11            1.00       {'alpha': 1, 'l1_ratio': 1}          -6.468807   
12            0.10     {'alpha'

In [144]:
pred_y = grid_model.predict(X_test)

In [145]:
mean_squared_error(y_test,pred_y)

2.387342642087474