In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [6]:
df = pd.read_csv("/content/sample_data/Advertising.csv")

In [7]:
X = df.drop(['sales'], axis=1)
y = df['sales']

In [8]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

In [9]:
poly_conv = PolynomialFeatures(degree=3, include_bias=False)

In [10]:
poly_feat = poly_conv.fit_transform(X)

In [11]:
poly_feat.shape

(200, 19)

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(poly_feat, y, test_size=0.3, random_state=101)

In [14]:
X_train.shape

(140, 19)

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
scaler = StandardScaler()

In [17]:
scaler.fit(X_train)

StandardScaler()

In [18]:
X_train = scaler.transform(X_train)

In [19]:
X_test = scaler.transform(X_test)

In [20]:
X_train[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

In [21]:
poly_feat

array([[2.30100000e+02, 3.78000000e+01, 6.92000000e+01, ...,
        9.88757280e+04, 1.81010592e+05, 3.31373888e+05],
       [4.45000000e+01, 3.93000000e+01, 4.51000000e+01, ...,
        6.96564990e+04, 7.99365930e+04, 9.17338510e+04],
       [1.72000000e+01, 4.59000000e+01, 6.93000000e+01, ...,
        1.46001933e+05, 2.20434291e+05, 3.32812557e+05],
       ...,
       [1.77000000e+02, 9.30000000e+00, 6.40000000e+00, ...,
        5.53536000e+02, 3.80928000e+02, 2.62144000e+02],
       [2.83600000e+02, 4.20000000e+01, 6.62000000e+01, ...,
        1.16776800e+05, 1.84062480e+05, 2.90117528e+05],
       [2.32100000e+02, 8.60000000e+00, 8.70000000e+00, ...,
        6.43452000e+02, 6.50934000e+02, 6.58503000e+02]])

In [22]:
from sklearn.linear_model import Ridge

In [23]:
ridge_model = Ridge(alpha=10)

In [24]:
ridge_model.fit(X_train,y_train)

Ridge(alpha=10)

In [25]:
test_pred = ridge_model.predict(X_test)

In [26]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [27]:
MAE = mean_absolute_error(y_test, test_pred)

In [28]:
MAE

0.5774404204714163

In [29]:
RMSE = np.sqrt(mean_squared_error(y_test,test_pred))

In [30]:
RMSE

np.float64(0.894638646131965)

In [31]:
from sklearn.linear_model import RidgeCV

In [32]:
ridge_cv_model = RidgeCV(alphas=(0.1, 1.0, 10.0),scoring = 'neg_mean_absolute_error')

In [33]:
ridge_cv_model.fit(X_train, y_train)

RidgeCV(scoring='neg_mean_absolute_error')

In [34]:
ridge_cv_model.alpha_

np.float64(0.1)

In [35]:
test_pred_2 = ridge_cv_model.predict(X_test)

In [36]:
MAE = mean_absolute_error(y_test, test_pred_2)

In [37]:
MAE

0.427377488434534

In [38]:
RMSE = np.sqrt(mean_squared_error(y_test, test_pred_2))

In [39]:
RMSE

np.float64(0.6180719926938822)

In [40]:
from sklearn.linear_model import LassoCV

In [41]:
lasso_cv_model = LassoCV(eps=0.1, n_alphas=100, cv=5)

In [42]:
lasso_cv_model.fit(X_train, y_train)

LassoCV(cv=5, eps=0.1)

In [43]:
lasso_cv_model.alpha_

np.float64(0.4943070909225831)

In [44]:
test_predictions = lasso_cv_model.predict(X_test)

In [45]:
MAE = mean_absolute_error(y_test, test_predictions)

In [46]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [47]:
MAE

0.6541723161252868

In [48]:
RMSE

np.float64(1.1308001022762548)

In [49]:
lasso_cv_model.coef_

array([1.002651  , 0.        , 0.        , 0.        , 3.79745279,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

In [50]:
from sklearn.linear_model import ElasticNetCV

In [53]:
elastic_model = ElasticNetCV(l1_ratio=[.1, .5, .7, .9, .95, .99, 1],n_alphas=100, eps=0.001,max_iter=1000000)

In [54]:
elastic_model.fit(X_train,y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=1000000)

In [55]:
elastic_model.l1_ratio

[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1]

In [56]:
elastic_model.l1_ratio_

np.float64(1.0)